### ISSUE TITLE
How to test jobs using XCTest?

### ISSUE THREAD

**Issue by henrypratt** [vapor/queues#126]
How would you go about testing a job since it is run on a thread that does not notify when it is complete? Right now I am just calling sleep(10) before running my asserts, but I would like to be able to know when an AsyncJob is done.

**Comment by 0xTim** [comment]
How are you running your tests? Have you seen https://github.com/vapor/queues/blob/main/Tests/QueuesTests/AsyncQueueTests.swift?

**Comment by henrypratt** [comment]
How would this work when using async/await for tests and queues?

**Comment by henrypratt** [comment]
Thanks!
