### ISSUE TITLE
Skip option for scheduling `.everySecond(skip: 10)`

### ISSUE THREAD

**Issue by paulober** [vapor/queues#130]
**Is your feature request related to a problem? Please describe.**
It's ugly to run a job like every 10 seconds as the system only offers seconds or minute but no quantifiers.

**Describe the solution you'd like**
Maybe an option to skip a certain amount of triggers like `skip: 10` can still trigger every second but would only invoke the job on the 10th and then on the 20th and so on.

**Describe alternatives you've considered**
And option to specify after how many seconds or minutes to trigger.

**Additional context**

**Comment by 0xTim** [comment]
Closing this in favour of https://github.com/vapor/queues/issues/133 - you can work around it with duplicating the code to schedule at the intervals you want but we could do with a better API
