### ISSUE TITLE
Remove deprecation for V1

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/queues#68]
We can remove this [deprecation](https://github.com/vapor/queues/blob/899151443f73915846aaf92188374dd68a3fe869/Sources/Queues/Application%2BQueues.swift#L6) now that we're about to tag a V1

**Comment by mcdappdev** [comment]
Already taken care of here: https://github.com/vapor/queues/pull/64/files#diff-bc532488367b0e1ea8dcc1a8b7e17103L6

Thanks!
