### ISSUE TITLE
Provide a Fluent-backed driver?

### ISSUE THREAD

**Issue by tonyarnold** [vapor/queues#70]
I've been working on porting the work I did for the earlier Jobs PostgreSQL driver over to the new Queues library, and I keep coming up against wanting to use Fluent to provide a `JobData` wrapper that could be constructed using Fluent. 

It got me to thinking: why not provide a single Queues driver that backs onto whatever Fluent-backed database the user is already using? 

Does this sound feasible?

**Comment by Andrewangeta** [comment]
Someone already started work on that :) https://github.com/m-barthelemy/vapor-queues-fluent-driver

**Comment by mcdappdev** [comment]
Beat me to it! :)
