### ISSUE TITLE
In process queues worker crash on Ctrl+c to exit server

### ISSUE THREAD

**Issue by thuotdwz** [vapor/queues#72]
I have found a small issue when making use of startInProcessJobs function to run in process worker.

In configure we call:

    app.queues.startInProcessJobs(on .default)

However when server is exited using ctrl+c, there will be an error printed from QueuesCommand deinit

    JobsCommand did not shutdown before deinit

 I think we need to QueuesCommand part of lifecycle so its shutdown function can be called properly?

THanks for your help!

**Comment by jdmcd** [comment]
Fixed by the latest release
