### ISSUE TITLE
Queues does not support Swift 5.2

### ISSUE THREAD

**Issue by siemensikkema** [vapor/queues#88]
Because Queues no longer supports 5.2 due to a few missing `self.` in QueueWorker.swift the test for Vapor with Queues as a provider now fail, see for example: https://github.com/vapor/vapor/pull/2511/checks?check_run_id=1272354381

I suggest we either drop down to 5.2 in the test or test for both 5.2 and 5.3. On a related note, the README also says Queues supports 5.2.

**Comment by jdmcd** [comment]
@siemensikkema good catch - we should probably just add back in those missing `self.` items. I will do that sometime this week!

**Comment by 0xTim** [comment]
Closed via #91
